version: '3'
services:
  db:
    container_name: db
    hostname: db
    image: "mysql"
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  api:
    image: inviewteam/best-final-api
    ports:
      - "1984:1984"
    links:
      - db
  front:
    image: inviewteam/best-final-front
    network_mode: host
    ports:
      - "80:80"
    depends_on:
      - api
